### ISSUE TITLE
ChapterTrackNumber

### ISSUE THREAD

**Issue by hubblec4** [cellar-wg/matroska-specification#315]
The specs say you have to use a track UID. Should we rename the `ChapterTrackNumber` element to `ChapterTrackUID`?

**Comment by dericed** [comment]
I agree this is confused, since there is a TrackNumber and TrackUID which are both uints and here the elements named ChapterTrackNumber is supposed to reference the "UID of the Track".

So if there's a Track with TrackNumber=1 and TrackUID=2 and the Chapter only applies to that Track, I'd guess that the ChapterTrackNumber should be set to 2, but is that right?

**Comment by hubblec4** [comment]
> So if there's a Track with TrackNumber=1 and TrackUID=2 and the Chapter only applies to that Track, I'd guess that the ChapterTrackNumber should be set to 2, but is that right?

Yes value 2 is correct. The Matroska specs say it is a UID.

**Comment by robUx4** [comment]
Fixed by #339
